development:
  adapter: postgresql
  encoding: unicode
  database: statixite_dev
  pool: 5
  username: rlafranchi
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: statixite_test
  pool: 5
  username: rlafranchi
  password:
  host: localhost
  port: 5432
